exports.FRIENDS = { friends: [ 9717342, 17051264, 17116749, 17177251, 8396792 ] };

exports.DM = { direct_message: 
   { id: 438346290867757060,
     id_str: '438346290867757056',
     text: 'this is a test',
     sender: 
      { id: 9717342,
        id_str: '9717342',
        name: 'Atul Varma',
        screen_name: 'toolness',
        location: 'Brooklyn',
        url: 'http://toolness.com',
        description: 'I work at the Mozilla Foundation and enjoy design, coding, and tinkering with stuff I don\'t know much about.',
        protected: false,
        followers_count: 2325,
        friends_count: 674,
        listed_count: 215,
        created_at: 'Fri Oct 26 18:57:52 +0000 2007',
        favourites_count: 488,
        utc_offset: -21600,
        time_zone: 'Central Time (US & Canada)',
        geo_enabled: true,
        verified: false,
        statuses_count: 844,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '1A1B1F',
        profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/130034970/twitter3_mozorg_backgroundimage.jpg',
        profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/130034970/twitter3_mozorg_backgroundimage.jpg',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/61009098/112964840_75_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/61009098/112964840_75_normal.jpg',
        profile_link_color: '2FC2EF',
        profile_sidebar_border_color: '181A1E',
        profile_sidebar_fill_color: '252429',
        profile_text_color: '666666',
        profile_use_background_image: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false },
     sender_id: 9717342,
     sender_id_str: '9717342',
     sender_screen_name: 'toolness',
     recipient: 
      { id: 2361284102,
        id_str: '2361284102',
        name: 'Mozilla Brooklyn',
        screen_name: 'mozbrooklyn',
        location: null,
        url: null,
        description: null,
        protected: false,
        followers_count: 0,
        friends_count: 5,
        listed_count: 0,
        created_at: 'Tue Feb 25 15:48:52 +0000 2014',
        favourites_count: 0,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 0,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'C0DEED',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
        profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        default_profile: true,
        default_profile_image: true,
        following: false,
        follow_request_sent: false,
        notifications: false },
     recipient_id: 2361284102,
     recipient_id_str: '2361284102',
     recipient_screen_name: 'mozbrooklyn',
     created_at: 'Tue Feb 25 16:14:34 +0000 2014',
     entities: { hashtags: [], symbols: [], urls: [], user_mentions: [] } } };

exports.FOLLOW = { event: 'follow',
  source: 
   { id: 2361284102,
     id_str: '2361284102',
     name: 'Mozilla Brooklyn',
     screen_name: 'mozbrooklyn',
     location: null,
     url: null,
     description: null,
     protected: false,
     followers_count: 0,
     friends_count: 5,
     listed_count: 0,
     created_at: 'Tue Feb 25 15:48:52 +0000 2014',
     favourites_count: 0,
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     verified: false,
     statuses_count: 0,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     default_profile: true,
     default_profile_image: true,
     following: false,
     follow_request_sent: false,
     notifications: false },
  target: 
   { id: 178796444,
     id_str: '178796444',
     name: 'Chris Lawrence',
     screen_name: 'chrislarry33',
     location: 'Brooklyn',
     url: 'http://t.co/y1fuHA9T',
     description: 'Senior Director of Mozilla Webmaker Mentor Community, lead Hive Learning Network, NYC. Father of Amelia.',
     protected: false,
     followers_count: 1142,
     friends_count: 1709,
     listed_count: 48,
     created_at: 'Sun Aug 15 18:32:07 +0000 2010',
     favourites_count: 51,
     utc_offset: -18000,
     time_zone: 'Eastern Time (US & Canada)',
     geo_enabled: true,
     verified: false,
     statuses_count: 5405,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'EEF2F6',
     profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/135714887/x727039ad3ff5fa137b4a74ee89eeb78.png',
     profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/135714887/x727039ad3ff5fa137b4a74ee89eeb78.png',
     profile_background_tile: true,
     profile_image_url: 'http://pbs.twimg.com/profile_images/437400420525146112/UVsRrK_g_normal.jpeg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/437400420525146112/UVsRrK_g_normal.jpeg',
     profile_banner_url: 'https://pbs.twimg.com/profile_banners/178796444/1358405722',
     profile_link_color: '4262C3',
     profile_sidebar_border_color: '0B0B0B',
     profile_sidebar_fill_color: 'FBFAFA',
     profile_text_color: '1C1F23',
     profile_use_background_image: true,
     default_profile: false,
     default_profile_image: false,
     following: false,
     follow_request_sent: false,
     notifications: false },
  created_at: 'Tue Feb 25 16:15:36 +0000 2014' };

exports.UNFOLLOW = { event: 'unfollow',
  source: 
   { id: 2361284102,
     id_str: '2361284102',
     name: 'Mozilla Brooklyn',
     screen_name: 'mozbrooklyn',
     location: null,
     url: null,
     description: null,
     protected: false,
     followers_count: 0,
     friends_count: 6,
     listed_count: 0,
     created_at: 'Tue Feb 25 15:48:52 +0000 2014',
     favourites_count: 0,
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     verified: false,
     statuses_count: 0,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     default_profile: true,
     default_profile_image: true,
     following: false,
     follow_request_sent: false,
     notifications: false },
  target: 
   { id: 178796444,
     id_str: '178796444',
     name: 'Chris Lawrence',
     screen_name: 'chrislarry33',
     location: 'Brooklyn',
     url: 'http://t.co/y1fuHA9T',
     description: 'Senior Director of Mozilla Webmaker Mentor Community, lead Hive Learning Network, NYC. Father of Amelia.',
     protected: false,
     followers_count: 1143,
     friends_count: 1709,
     listed_count: 48,
     created_at: 'Sun Aug 15 18:32:07 +0000 2010',
     favourites_count: 51,
     utc_offset: -18000,
     time_zone: 'Eastern Time (US & Canada)',
     geo_enabled: true,
     verified: false,
     statuses_count: 5405,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'EEF2F6',
     profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/135714887/x727039ad3ff5fa137b4a74ee89eeb78.png',
     profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/135714887/x727039ad3ff5fa137b4a74ee89eeb78.png',
     profile_background_tile: true,
     profile_image_url: 'http://pbs.twimg.com/profile_images/437400420525146112/UVsRrK_g_normal.jpeg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/437400420525146112/UVsRrK_g_normal.jpeg',
     profile_banner_url: 'https://pbs.twimg.com/profile_banners/178796444/1358405722',
     profile_link_color: '4262C3',
     profile_sidebar_border_color: '0B0B0B',
     profile_sidebar_fill_color: 'FBFAFA',
     profile_text_color: '1C1F23',
     profile_use_background_image: true,
     default_profile: false,
     default_profile_image: false,
     following: false,
     follow_request_sent: false,
     notifications: false },
  created_at: 'Tue Feb 25 16:15:51 +0000 2014' };

exports.MENTION = { created_at: 'Tue Feb 25 16:16:46 +0000 2014',
  id: 438346846243942400,
  id_str: '438346846243942400',
  text: '@mozbrooklyn this is a test!',
  source: 'web',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 2361284102,
  in_reply_to_user_id_str: '2361284102',
  in_reply_to_screen_name: 'mozbrooklyn',
  user: 
   { id: 9717342,
     id_str: '9717342',
     name: 'Atul Varma',
     screen_name: 'toolness',
     location: 'Brooklyn',
     url: 'http://toolness.com',
     description: 'I work at the Mozilla Foundation and enjoy design, coding, and tinkering with stuff I don\'t know much about.',
     protected: false,
     followers_count: 2325,
     friends_count: 674,
     listed_count: 215,
     created_at: 'Fri Oct 26 18:57:52 +0000 2007',
     favourites_count: 488,
     utc_offset: -21600,
     time_zone: 'Central Time (US & Canada)',
     geo_enabled: true,
     verified: false,
     statuses_count: 845,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: '1A1B1F',
     profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/130034970/twitter3_mozorg_backgroundimage.jpg',
     profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/130034970/twitter3_mozorg_backgroundimage.jpg',
     profile_background_tile: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/61009098/112964840_75_normal.jpg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/61009098/112964840_75_normal.jpg',
     profile_link_color: '2FC2EF',
     profile_sidebar_border_color: '181A1E',
     profile_sidebar_fill_color: '252429',
     profile_text_color: '666666',
     profile_use_background_image: true,
     default_profile: false,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweet_count: 0,
  favorite_count: 0,
  entities: 
   { hashtags: [],
     symbols: [],
     urls: [],
     user_mentions: [{
      "screen_name": "mozbrooklyn",
      "name": "Mozilla Brooklyn",
      "id": 2361284102,
      "id_str": "2361284102",
      "indices": [0, 0] // This is fake
    }] },
  favorited: false,
  retweeted: false,
  filter_level: 'medium',
  lang: 'en' };
